apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: estadisticas-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: estadisticas-service
  minReplicas: 2 # Según la pauta (2 -> 6 réplicas)
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Umbral del 50% justificado para aguantar las avalanchas de hinchas de la serie del King